=== Pablo-Gallego/LLMM/Ejercicios_2º_trimestre/dtd/Futbol.dtd
<!ELEMENT Futbol (equipos)>
<!ELEMENT equipos (equipo)>
    <!ELEMENT equipo ((Nombre)+, Copas, Jugadores, Partidosjugados, Estadio)>
        <!ELEMENT Nombre (#PCDATA)>
        <!ELEMENT Copas (#PCDATA)>
        <!ELEMENT Jugadores (Pichichi, Tarjetas, Equipacion )>
            <!ELEMENT Pichichi ((Nombre)+, FechaNacimiento, Goles)>
                <!ELEMENT Nombre (#PCDATA)>
                <!ELEMENT FechaNacimiento (#PCDATA)>
                <!ELEMENT Goles (#PCDATA)>

            <!ELEMENT Tarjetas (Rojas, Amarillas)>
                <!ELEMENT Rojas (#PCDATA)>
                <!ELEMENT Amarillas (#PCDATA)>  

            <!ELEMENT Equipacion (Primera, Segunda)>
                <!ELEMENT Primera (#PCDATA)>
                <!ELEMENT Segunda (#PCDATA)> 

        <!ELEMENT Partidosjugados (Ganados, Empatados, Perdidos)>
            <!ELEMENT Ganados (#PCDATA)>
            <!ELEMENT Empatados (#PCDATA)>
            <!ELEMENT Perdidos (#PCDATA)>

        <!ELEMENT Estadio (Nombre, Capacidad)>
            <!ELEMENT Nombre (#PCDATA)>
            <!ELEMENT Capacidad (#PCDATA)>

=== Pablo-Gallego/LLMM/Ejercicios_2º_trimestre/dtd/Futbol.xml
<?xml version="1.0"?>
<!DOCTYPE Futbol SYSTEM "Futbol.dtd">
<Futbol>
    <equipos>
        <equipo>
            <Nombre>Betis</Nombre>
            <Copas>0</Copas>
            <Jugadores>
                <Pichichi>
                    <NombrePi>Joaquin</NombrePi>
                    <FechaNacimiento>1980-10-10</FechaNacimiento>
                    <Goles>100</Goles>
                </Pichichi>
                <Tarjetas>
                    <Rojas>0</Rojas>
                    <Amarillas>1</Amarillas>
                </Tarjetas>
                <Equipacion>
                    <Primera>blanco y verde</Primera>
                    <Segunda>azul y blanca</Segunda>
                </Equipacion>
            </Jugadores>
            <Partidosjugados>
                <Ganados>100</Ganados>
                <Empatados>10</Empatados>
                <Perdidos>50</Perdidos>
            </Partidosjugados>
            <Estadio>
                <NombreEs>Benito Villamar√≠n</NombreEs>
                <Capacidad>60000</Capacidad>
            </Estadio>
        </equipo>
    </equipos>
</Futbol>
