=== Pablo-Gallego/LLMM/Ejercicios_2º_trimestre/dtd/note.dtd
<!ELEMENT note (to, from, heading, body)>
<!ELEMENT to (#PCDATA)><!-- PCDATA introducira -->
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (mensaje, fecha)><!--cambio PCDATA a los elementos que contiene-->
<!ELEMENT mensaje (#PCDATA)>
<!ELEMENT fecha (dia, mes, ano)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT ano (#PCDATA)>

=== Pablo-Gallego/LLMM/Ejercicios_2º_trimestre/dtd/note.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "note.dtd">
<note>
  <to>Tove</to>
  <from>
      <email>email@gmail.com</email>
      <nombre>Pablo</nombre>
  </from>
  <heading>Reminder</heading>
  <body>
      <mensaje>hola</mensaje>
      <fecha>
          <dia>1</dia>
          <mes>enero</mes>
          <ano>2000</ano>
      </fecha>
  </body>
</note>
