=== Pablo-Gallego/LLMM/Ejercicios_2º_trimestre/xsd/Calendario.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="calendario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="trimestre">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="asignatura" minOccurs="1" maxOccurs="6">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="tema" minOccurs="1" maxOccurs="10"/>
                    <xs:element name="fechaExamenes" type="xs:date" maxOccurs="unbounded"/>
                  </xs:sequence>
                  <xs:attribute name="nombre" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ciclo" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Refencencia -->
  <xs:element name="tema">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="notamedia">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="teoria" type="xs:float" minOccurs="1" maxOccurs="10"/>
              <xs:element name="practica" type="xs:float" minOccurs="1" maxOccurs="10"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="tema" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Pablo-Gallego/LLMM/xsd/Calendario.xml
<?xml version="1.0" encoding="UTF-8"?>
<calendario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="calendario.xsd">
    <trimestre ciclo="primero">
        <asignatura nombre="LLMM">
            <tema tema="4">
                <nombre>RSS</nombre>
                <notamedia>
                    <teoria>5.5</teoria>
                    <practica>5.5</practica>
                </notamedia>
            </tema>
            <tema tema="5">
                <nombre>Schema</nombre>
                <notamedia>
                    <teoria>5.5</teoria>
                    <practica>5.5</practica>
                </notamedia>
            </tema>
            <fechaExamenes>2021-11-09</fechaExamenes>
        </asignatura>
        <asignatura nombre="PLAR">
            <tema tema="5">
                <nombre>vlan</nombre>
                <notamedia>
                    <teoria>5.5</teoria>
                    <practica>5.5</practica>
                </notamedia>
            </tema>
            <tema tema="6">
                <nombre>Switch</nombre>
                <notamedia>
                    <teoria>5.5</teoria>
                    <practica>5.5</practica>
                </notamedia>
            </tema>
            <fechaExamenes>2022-02-14</fechaExamenes>
        </asignatura>
    </trimestre>
</calendario>
