=== Pablo-Gallego/LLMM/Ejercicios_2º_trimestre/xsd/Consolas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="consolas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="consola" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plataforma" type="xs:string"/>
                            <xs:element name="version" type="xs:string"/>
                            <xs:element name="juegos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="accion" type="xs:string">
                                            
                                        </xs:element>
                                        <xs:element name="rol" type="xs:string">
                                            
                                        </xs:element>
                                        <xs:element name="arcade" type="xs:string">
                                            
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="fechaLanzamiento" type="xs:date"/>
                            <xs:element name="exito">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ventas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="numero" type="xs:integer"/>
                                                    <xs:element name="mes" type="xs:string"/>
                                                    <xs:element name="ano" type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Pablo-Gallego/LLMM/Ejercicios_2º_trimestre/xsd/Consolas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<consolas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
xsi:noNamespaceSchemaLocation="Consolas.xsd">
    <consola>
        <plataforma>Ps</plataforma>
        <version>5</version>
        <juegos>
            <accion>N1</accion>
            <rol>N2</rol>
            <arcade>N3</arcade>
        </juegos>
        <fechaLanzamiento>2020-02-02</fechaLanzamiento>
        <exito>
            <ventas>
                <numero>5</numero>
                <mes>ENERO</mes>
                <ano>2020</ano>
            </ventas>
        </exito>
    </consola>
</consolas>
