<?xml version="1.0"?>
<!DOCTYPE NEWSPAPER [
<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
    <!ELEMENT HEADLINE (#PCDATA)>
    <!ELEMENT BYLINE (#PCDATA)>
    <!ELEMENT LEAD (#PCDATA)>
    <!ELEMENT BODY (#PCDATA)>
    <!ELEMENT NOTES (#PCDATA)>
<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>
<!ENTITY NEWSPAPER "Vervet Logic Times, ">
<!ENTITY PUBLISHER "Vervet Logic Press">
<!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press, ">
]>
<NEWSPAPER>
    <ARTICLE AUTHOR="Vervet Logic Times" EDITION="Nueva" EDITOR="Paco" DATE="Hoy">
        <HEADLINE>Hoy</HEADLINE>
        <BYLINE>No</BYLINE>
        <LEAD>Se</LEAD>
        <BODY>Trabaja</BODY>
        <NOTES>&COPYRIGHT;&NEWSPAPER;&PUBLISHER;</NOTES>
    </ARTICLE>
</NEWSPAPER>