=== Pablo-Gallego/LLMM/xsd/ejercicios.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Ejercicios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="telefono">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[+][0-9]{11}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="password">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="5"/>
              <xs:maxLength value="8"/>
              <xs:pattern value="[a-zA-Z0-9]{8}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="DNI">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[0-9]{8}[a-zA-Z]"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="expresion" type="expresiones"/>
        <xs:element name="viagra" type="variacionesviagra"/>
        <xs:element name="gmail">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[a-z0-9]*[@][a-z]*[.][a-z]*"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="gmail2">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[_]*[a-z0-9]{6,50}[@][a-z]{1,10}[.][a-z]{2,6}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="sexo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="femenino" default="f">
                <xs:simpleType >
                  <xs:restriction base="xs:string">
                    <xs:pattern value="f|F|Mujer|M|femenino" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="masculino" default="m">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="m|M|Hombre|H|masculino"/>
                    </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="sexos"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="expresiones">
    <xs:restriction base="xs:string">
      <xs:enumeration value="tonteria"/>
      <xs:enumeration value="maldito"/>
      <xs:enumeration value="caray"/>
      <xs:enumeration value="caramba"/>
      <xs:enumeration value="madre"/>
      <xs:enumeration value="mia"/>
      <xs:enumeration value="ostras"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="variacionesviagra">
    <xs:restriction base="xs:string">
      <xs:enumeration value="v1agra"/>
      <xs:enumeration value="vi@gra"/>
      <xs:enumeration value="v1@gra"/>
      <xs:enumeration value="v1@gr@"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="sexos">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
            <xs:enumeration value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Pablo-Gallego/LLMM/xsd/ejercicios.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Ejercicios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicios.xsd">
  <telefono>+34123456789</telefono>
  
  <password>Aa123456</password>
  
  <DNI>12345678A</DNI>
  
  <expresion>caray</expresion>
  
  <viagra>v1agra</viagra>
  
  <gmail>pepe87@gmail.com</gmail>

  <gmail2>_pepe87@gmail.com</gmail2>

  <sexo>
    <femenino></femenino>
    <masculino></masculino>
  </sexo>

</Ejercicios>
