<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE declaraciones [
   <!--Elementos-->
   <!ELEMENT declaraciones (constante | tipo_de_dato | variable)*>
      <!ELEMENT constante (#PCDATA)> 
      <!ELEMENT tipo_de_dato (#PCDATA)>
      <!ELEMENT variable (#PCDATA)>
   
   <!--Atributos-->
   <!ATTLIST constante valor CDATA #REQUIRED>
   <!ATTLIST variable tipo CDATA #REQUIRED>
]>

<declaraciones>
   <constante valor="3.141592">PI</constante>
   <tipo_de_dato>longitud</tipo_de_dato>
   <variable tipo="real">radio</variable>
   <variable tipo="formula">area</variable>
</declaraciones>