=== Pablo-Gallego/LLMM/Ejercicios_3º_trimestre/dtd/medicamentos.dtd
<!ELEMENT medicamentos (medicamento+)>
<!ELEMENT medicamento (nombre,administrador,dosis)>
    <!ELEMENT nombre (generico,comercial+)>
        <!ELEMENT generico (#PCDATA)>
        <!ELEMENT comercial (#PCDATA)>
    <!ELEMENT administrador (tiemposiguiente)>
        <!ELEMENT tiemposiguiente (horas)>
            <!ELEMENT horas (#PCDATA)>
    <!ELEMENT dosis (cantidad)>
        <!ELEMENT cantidad (g|mg)>
            <!ELEMENT g (#PCDATA)>
            <!ELEMENT mg (#PCDATA)>

<!--Atributos-->
<!ATTLIST nombre id CDATA #REQUIRED>
<!ATTLIST administrador tipo (intramuscular|oral) "">

=== Pablo-Gallego/LLMM/Ejercicios_3º_trimestre/dtd/medicamentos.xml
<?xml version="1.0"?>
<!DOCTYPE medicamentos SYSTEM "medicamentos.dtd">
<medicamentos>
    <medicamento>
    <nombre id="Med1">
        <generico>espidifen</generico>
        <comercial>dalsy</comercial>
    </nombre>
    <administrador tipo="oral">
        <tiemposiguiente>
            <horas>8</horas>
        </tiemposiguiente>
    </administrador><!--Solo admite el tipo de datos de cadena de texto, por eso el contenido es CDATA y no se le pueden poner condiciones. -->
    <dosis>
        <cantidad>
            <g>1</g>
        </cantidad>
    </dosis>
    </medicamento>
    <medicamento>
        <nombre id="Med2">
            <generico>espidifen</generico>
            <comercial>espidifen</comercial>
            <comercial>rapidin</comercial>
        </nombre>
        <administrador tipo="intramuscular">
            <tiemposiguiente>
                <horas>12</horas>
            </tiemposiguiente>
        </administrador>
        <dosis>
            <cantidad>
                <mg>0,5</mg>
            </cantidad>
        </dosis>
    </medicamento>
</medicamentos>
